### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by ewhauser** [stripe/sbt-bazel#2]
Great project - fills a nice gap in converting sbt projects to Bazel. I tried this on a large sbt project and it just hangs loading the project definition. Tried turning up debug logging, but didn't get an interesting messages.

Realize it is early going from the commit history. Happy to debug a bit and file improvements. Can you add a minimum `README` to the repo with the dev flow?

**Comment by beala-stripe** [comment]
We'd love to have more eyes on this, and contributions are certainly welcome. A readme and license should be forthcoming in the next few days. Please hang tight :-)

**Comment by beala-stripe** [comment]
Hey just wanted to give you a quick update here. We're in the process of getting a license for this repo, but it looks like the earliest that will be is sometime next week.

**Comment by beala-stripe** [comment]
Readme added. #3
