### ISSUE TITLE
Rethink migration: use bloop to go from sbt -> bazel

### ISSUE THREAD

**Issue by jvican** [stripe/sbt-bazel#4]
I'd like to suggest using Bloop (https://scalacenter.github.io/bloop/) to migrate builds in other build tools to Bazel.
  
Bloop targets Maven, Gradle, mill and sbt and has plugins for all of these build systems. Bloop extracts information about build projects so that we can compile, test and run (which are the tasks that are currently supported in Bazel too), as well as powering our BSP server that needs information about artifacts too.
  
The extraction process in the plugins outputs a Bloop project per Maven configuration. For a normal project in, say, sbt, the plugin will create two Bloop projects by default, one for the configuration `Compile` and another one for the configuration `Test`. There is a one-to-one mapping between Bloop projects and Bazel targets, which simplifies a lot the migration, and we not only support the `Compile` and `Test` configurations, but also other user-defined configurations (like `IntegrationTest`).
  
Needless to say, this extraction process in all the previous builds is complicated and requires a lot of foo about the build systems that targets. By targeting bloop configuration files, this migration tool could be more effective, simpler, and easier to maintain (for example, by looking at the sources of the plugin I've realized some bits of the logic extracting classpath are not performed correctly; targeting bloop configuration file format would solve this problem).
  
The configuration file format that describes a bloop project is well-documented: https://scalacenter.github.io/bloop/docs/configuration-format/, so it is a stable foundation for this migration tool. The configuration file format has been designed with future compatibility/additions in mind so that we never have to jump to Bloop 2.0 (I cannot promise this, but there's a strong guarantee this will be the case. If it weren't, rest assured there will be a tool to transform between 1.x config files to 2.x config files).
  
By targeting bloop, the only thing that a migration tool needs to do is to translate from a JSON file to a Skylark file. This is a much simpler task than the current scope of the project and it's something that we can deliver to users much quickly.
  
So, all in all, this suggestion would allow going from Maven, sbt, Gradle and mill builds to Bazel for those users that want to give source dependencies a try. Let me know what are your thoughts. /cc @oscar-stripe

**Comment by jvican** [comment]
Doesn't look like there's interest in this. If someone wants to give this a try, let me know privately and I'll be happy to assist.

**Comment by johnynek** [comment]
Jorge, I think there isn't much interest in this project since we have found migration isn't that hard for most projects and the team would rather do it by hand.

I think a migration tool is interesting from a bazel perspective, but I don't know who is motivated to work on it at the moment: you only migrate once, and people using bazel generally don't make money on it. I think it would likely be funded by someone who has a huge number of sbt repos, a consulting company helping people adopt bazel, or a passionate OSS contributor who enjoyed working on the problem.

**Comment by jvican** [comment]
Hi @johnynek, thanks for the feedback and explaining the current state of things, that looks like a sensible approach.
